### ISSUE TITLE
Hi , pyRoxy problem 

### ISSUE THREAD

**Issue by zartland** [lucthienphong1120/5xDDoS#1]
PyRoxy install but I installed but the problem persists

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/5xDDoS/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'

**Comment by lucthienphong1120** [comment]
pip install pyroxy
