### ISSUE TITLE
yarl error

### ISSUE THREAD

**Issue by xXxF4T4LITYxXx** [lucthienphong1120/5xDDoS#4]
Failed to build yarl
ERROR: Could not build wheels for yarl, which is required to install pyproject.toml-based projects

**Comment by xXxF4T4LITYxXx** [comment]
yarl/_quoting_c.c:198:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
Successfully built PyRoxy
Failed to build yarl
ERROR: Could not build wheels for yarl, which is required to install pyproject.toml-based projects

**Comment by lucthienphong1120** [comment]
The error message suggests that the file 'longintrepr.h' is missing, which is needed to build the 'yarl' package. This file is part of the Python development headers and needs to be installed on your system before you can successfully build the package.

To fix this error, you can try installing the Python development headers:

```
sudo apt-get install python-dev
```

After installing the Python development headers, try installing your Python app again. If the error persists, you can try upgrading pip and setuptools by running the following command:

```
pip install --upgrade pip setuptools
```

If the issue still persists, you can try installing the 'yarl' package separately using pip:

```
pip install yarl
```
